version: '3' 
services:
  web:
    image: nginx:latest
    ports:
      - "9000:80"
    depends_on:
      - php
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/

  php:
    build: ./php
    volumes:
      - ./src:/var/www/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=localhost #mysqlサービス名を指定
      - PMA_USER=root
      - PMA_PASSWORD=stoful2022
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions